# Generated by Django 2.1.5 on 2019-01-20 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=1)),
                ('value', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('turn', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokergame.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_chips', models.IntegerField(default=20)),
                ('AI', models.BooleanField(default=False)),
                ('current_bet', models.IntegerField(default=0)),
                ('winner', models.BooleanField(default=False)),
                ('turn', models.BooleanField(default=False)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pokergame.Card')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokergame.Player'),
        ),
    ]
